### PR TITLE
fix cmake configuration list on Windows

### PR DESCRIPTION
**Pull request by alex85k**
Currently cmake gives errors on Windows (seems to be cmake bug-feature https://cmake.org/Bug/view.php?id=6788 )

Workaround from osmium-tool.
Maybe appveyor would be good too...

### CODE REVIEW

**Comment by joto** [comment]
If the setting isn't in `common.cmake` any more it has to be set in the `CMakeLists.txt` in the subdirectories, too. This way you can build the subdirectories by themselves.

**Comment by alex85k** [comment]
Tried to fix the structure of the build scripts as adviced.
Tests were not working too, simplified them. Separate build seem to work too.

**Comment by alex85k** [comment]
(looking into travis issues)

**Comment by alex85k** [comment]
Seems to work now...

**Pull request merged**
